window.JOBS_DATA = [
  {"date": "2026-05-03", "location": "Bath, UK", "company": "Clover Studio", "title": "Part 3 architect", "salary": "", "link": "https://www.dezeenjobs.com/job/clover-studio-architect-part-iii-bristol-bath-south-west-1088417/"},
  {"date": "2026-05-09", "location": "Bristol or Ross-on-Wye, UK", "company": "Co&Co Architects", "title": "Architect", "salary": "", "link": "https://www.dezeenjobs.com/job/co-co-architects-architect-1089399/"},
  {"date": "2026-05-09", "location": "Bristol, UK", "company": "HTA Design", "title": "Architect", "salary": "£39,000 – £44,000", "link": "https://www.dezeenjobs.com/job/hta-design-architect-1084768/"},
  {"date": "2026-05-09", "location": "West Sussex, UK", "company": "George and James Architects", "title": "Architect/Architectural Technologist", "salary": "", "link": "https://www.dezeenjobs.com/job/george-and-james-architects-architect-architectural-technologist-1083487/"},
  {"date": "2026-05-09", "location": "Bath, UK", "company": "Nick Shipp Architects", "title": "Architect", "salary": "", "link": "https://www.dezeenjobs.com/job/nick-shipp-architects-ltd-architect-at-nick-shipp-architects-1082647/"},
  {"date": "2026-05-09", "location": "Berkshire, UK", "company": "iB Architects", "title": "Architect/Technologist", "salary": "£35,000 – £40,000", "link": "https://www.dezeenjobs.com/job/ib-architects-architect-technologist-1078537/"},
  {"date": "2026-05-09", "location": "Bristol, UK", "company": "WH Architects", "title": "Part 2/3 Architect/Architectural Technologist", "salary": "", "link": "https://www.dezeenjobs.com/job/wh-architects-part-2-3-architect-architectural-technlogist-1071236/"},
  {"date": "2026-05-09", "location": "Bristol, UK", "company": "Oxford Architects", "title": "Architect", "salary": "£35,000", "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-architect-1070749/"},
  {"date": "2026-05-09", "location": "Bristol, UK", "company": "Oxford Architects", "title": "Post-Part 2 Architectural Assistant", "salary": "£30,000", "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-post-part-2-architectural-assistant-1070769/"},
  {"date": "2026-05-09", "location": "Oxfordshire, UK", "company": "Emma Kirby Design", "title": "In-house Architect/Architectural Technician", "salary": "", "link": "https://www.dezeenjobs.com/job/emma-kirby-design-ltd-in-house-architect-architectural-technician-1027052/"},
  {"date": "2026-05-11", "location": "Worcester, UK", "company": "DJD Architects", "title": "Part 2 architectural assistant", "salary": "£30,000 - £35,000", "link": "https://www.dezeenjobs.com/job/djd-architects-part-2-architectural-assistant-1088870/"},
  {"date": "2026-05-11", "location": "Cotswolds, UK", "company": "Haines Gadd Greaves", "title": "Project architect", "salary": "Undisclosed", "link": "https://www.dezeenjobs.com/job/haines-gadd-greaves-project-architect-1089633/"}
];
window.JOBS_UPDATED = "11 May 2026";