// Auto-generated by Dezeen Jobs tracker (web search fallback)
window.JOBS_DATA = [
  {
    "date": "2026-05-11",
    "location": "Bristol or Ross-on-Wye, UK",
    "company": "Co&Co Architects",
    "title": "Architect",
    "salary": "",
    "link": "https://www.dezeenjobs.com/job/co-co-architects-architect-1089399/"
  },
  {
    "date": "2026-05-11",
    "location": "Bristol, UK",
    "company": "Oxford Architects",
    "title": "Architect",
    "salary": "",
    "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-architect-1070749/"
  },
  {
    "date": "2026-05-11",
    "location": "Bristol, UK",
    "company": "Oxford Architects",
    "title": "Post-Part 2 Architectural Assistant",
    "salary": "",
    "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-post-part-2-architectural-assistant-1070769/"
  },
  {
    "date": "2026-05-11",
    "location": "Worcester, UK",
    "company": "DJD Architects",
    "title": "Part 2 Senior Architectural Assistant",
    "salary": "",
    "link": "https://www.dezeenjobs.com/job/djd-architects-part-2-senior-architectural-assistant-1037396/"
  }
];
window.JOBS_UPDATED = "11 May 2026 (web search — Chrome scrape will add more on next run)";
