window.JOBS_DATA = [
  {"date": "2026-05-18", "location": "Bath, UK", "company": "Clover Studio", "title": "Part 3 architect", "salary": "", "link": "https://www.dezeenjobs.com/job/clover-studio-architect-part-iii-bristol-bath-south-west-1088417/"},
  {"date": "2026-05-18", "location": "Bristol, UK", "company": "WH Architects", "title": "Architectural assistant", "salary": "", "link": "https://www.dezeenjobs.com/job/wh-architects-architectural-assistant-1049758/"},
  {"date": "2026-05-18", "location": "Bristol, UK", "company": "WH Architects", "title": "Part 2/3 architect/architectural technologist", "salary": "", "link": "https://www.dezeenjobs.com/job/wh-architects-part-2-3-architect-architectural-technlogist-1071236/"},
  {"date": "2026-05-18", "location": "Bristol or Ross-on-Wye, UK", "company": "Co&Co Architects", "title": "Architect", "salary": "", "link": "https://www.dezeenjobs.com/job/co-co-architects-architect-1089399/"},
  {"date": "2026-05-18", "location": "Bristol, UK", "company": "Oxford Architects", "title": "Architect", "salary": "£35,000", "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-architect-1070749/"},
  {"date": "2026-05-18", "location": "Bristol, UK", "company": "Oxford Architects", "title": "Post-Part 2 architectural assistant", "salary": "", "link": "https://www.dezeenjobs.com/job/oxford-architects-llp-post-part-2-architectural-assistant-1070769/"},
  {"date": "2026-05-18", "location": "Cotswolds, UK", "company": "James Mackintosh Architects", "title": "Senior architect/architectural technician", "salary": "", "link": "https://www.dezeenjobs.com/job/james-mackintosh-architects-senior-architect-architectural-technician-1050959/"},
  {"date": "2026-05-18", "location": "Cotswolds, UK", "company": "The Bamford Collection", "title": "Architect", "salary": "", "link": "https://www.dezeenjobs.com/job/bamford-collection-recruitment-manager-1079133/"},
  {"date": "2026-05-18", "location": "Berkshire, UK", "company": "iB Architects", "title": "Architect/technologist", "salary": "£35,000-£40,000", "link": "https://www.dezeenjobs.com/job/ib-architects-architect-technologist-1078537/"},
  {"date": "2026-05-18", "location": "Stroud, UK", "company": "Common Works", "title": "Architect", "salary": "", "link": "https://www.dezeenjobs.com/job/common-works-architect-1062874/"},
  {"date": "2026-05-18", "location": "Oxfordshire, UK", "company": "WWA Studios", "title": "Part 3 architect/architectural technician", "salary": "", "link": "https://www.dezeenjobs.com/job/wwa-studios-part-3-architect-architectural-technician-1091142/"},
  {"date": "2026-05-18", "location": "Oxfordshire, UK", "company": "WWA Studios", "title": "Part 2/3 architectural assistant/project architect", "salary": "", "link": "https://www.dezeenjobs.com/job/archadia-uk-ltd-t-a-wwa-part-2-architectural-assistant-part-3-project-architect-1074230/"},
  {"date": "2026-05-18", "location": "Oxfordshire, UK", "company": "HÁM", "title": "Experienced CAD technician", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Oxfordshire, UK", "company": "Emma Kirby Design", "title": "In-house architect/architectural technician", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "West Sussex, UK", "company": "George and James Architects", "title": "Architect/architectural technologist", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "North Cotswolds, UK", "company": "Charlie Luxton Design", "title": "Part 2 architectural assistant/recently qualified architect", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Worcester, UK", "company": "DJD Architects", "title": "Part 2 senior architectural assistant", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Cotswolds, UK", "company": "Haines Gadd Greaves", "title": "Project architect", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Oxford, UK", "company": "Design Storey", "title": "Architect", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Oxford, UK", "company": "Riach Architects", "title": "Part 2 architectural assistant", "salary": "", "link": ""},
  {"date": "2026-05-18", "location": "Edinburgh, Scotland", "company": "Moleta Munro", "title": "Showroom and sales assistant", "salary": "", "link": ""},
];
window.JOBS_UPDATED = "18 May 2026";